const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {test}=require('node:test');
const source=fs.readFileSync('src/EduMaster.Web/wwwroot/learning/learning.js','utf8').split('// End learning PDF module')[0];
class Element {constructor(tag){this.tag=tag;this.children=[];this.textContent='';}append(...children){this.children.push(...children);}setAttribute(){}remove(){}click(){return this.onclick?.();}}
function setup(fetch){const downloads=[];class TestURL extends URL {static createObjectURL(){return 'blob:pdf';}static revokeObjectURL(){}}const context={window:{},document:{body:new Element('body'),createElement:tag=>{const el=new Element(tag);if(tag==='a')el.click=()=>downloads.push(el.download);return el;}},URL:TestURL,AbortController,fetch,setTimeout:(fn,ms)=>ms===60000?0:setTimeout(fn,ms),clearTimeout};vm.runInNewContext(source,context);return {...context.window.LearningPdf,downloads};}
const group={title:'반응량',items:[{jobId:'a'.repeat(32),pdfReportId:'b'.repeat(32)}]},options={apiBase:new URL('https://example.test/edumaster/api/'),access:'test-token'};
const pdfResponse=()=>new Response(new Blob(['%PDF-'+'.'.repeat(2000)]),{headers:{'Content-Type':'application/pdf'}});
async function finish(button){for(let i=0;i<100&&button.disabled;i++)await new Promise(resolve=>setTimeout(resolve,5));assert.equal(button.disabled,false);}
test('repeated downloads fetch only the stored set PDF with authentication, without creating reports',async()=>{const calls=[],pdf=setup(async(url,init)=>{calls.push({url:String(url),init});return pdfResponse();});for(let i=0;i<2;i++){const action=pdf.createAction(group,options),button=action.children[0];button.click();await finish(button);assert.match(action.children[1].textContent,/다운로드를 시작/);}assert.equal(calls.length,2);assert.ok(calls.every(call=>call.url.endsWith('/learning/jobs/'+group.items[0].jobId+'/pdf')&&!call.init.method&&call.init.headers.Authorization==='Bearer test-token'));assert.equal(pdf.downloads.length,2);assert.equal(pdf.buildReport,undefined);});
test('a legacy set with no saved PDF disables download and does not reconstruct a report',()=>{let calls=0;const pdf=setup(async()=>{calls++;return pdfResponse();}),action=pdf.createAction({...group,items:[{jobId:'a'.repeat(32)}]},options);assert.equal(action.children[0].disabled,true);assert.match(action.children[1].textContent,/다시 눌러/);assert.equal(calls,0);});
test('stage tab changes and repeated clicks cannot trigger concurrent downloads',async()=>{let resolve,calls=0;const pdf=setup(()=>{calls++;return new Promise(r=>resolve=r);}),first=pdf.createAction(group,options),second=()=>pdf.createAction(group,options);first.children[0].click();first.children[0].click();const another=second();assert.equal(another.children[0].disabled,true);another.children[0].click();assert.equal(calls,1);resolve(pdfResponse());await finish(first.children[0]);await finish(another.children[0]);assert.equal(pdf.downloads.length,1);});
test('missing PDF never calls the report creator and restores retry after error',async()=>{const calls=[],pdf=setup(async(url,init)=>{calls.push({url:String(url),init});return Response.json({error:'저장된 PDF가 없습니다'},{status:404});}),action=pdf.createAction(group,options);action.children[0].click();await finish(action.children[0]);assert.match(action.children[1].textContent,/저장된 PDF가 없습니다/);assert.equal(calls.length,1);assert.equal(pdf.downloads.length,0);});
